import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
// import { ReactNode } from "react";
import Navbar from "@/components/Navbar";
import ToasterContext from "./context/ToasterContext";
import { ThemeProvider } from "./theme-provider";
import Assist from "@/components/aigent/Assist";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
       
          <ToasterContext />
          <SidebarProvider>
      {/* <div className="flex flex-row min-h-screen"> */}
        <AppSidebar />
        <main className="flex-grow">
          <div className="flex flex-col min-h-screen p-4 bg-gray-100 dark:bg-zinc-900">
            <Navbar />
            <div className="flex-grow w-full mt-4 rounded-lg shadow-lg p-6">
              {children}
            </div>
            
             <Assist/>
          </div>
        </main>
      {/* </div> */}
    </SidebarProvider>
      {/* <Assist/> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
